### ISSUE TITLE
Broken on OSX when launching VS Code from finder/dock: not picking up system locale

### ISSUE THREAD

**Issue by willmcgugan** [joslarson/black-vscode#9] opened 2018-05-02 14:51 UTC
I can't get this extension to work on OSX.

Noting happens when I run "Format Document" or "Format Selection". When I enable "black.debug" there is no debug output in the debug console.

I've tried setting "black.path" explicitly, I've set "python.formatting.provider" to "none", and other combinations of settings, to no avail. The black commands works from the command line.

What am I missing?

**Comment by joslarson** [comment] 2018-05-02 20:39
I don't have any ideas right off. I'm a Mac user myself, so I think it's safe to assume that's not the issue.

What was your `black.path` set to when you tried it that way? Also when you set `black.debug` to `true` the output doesn't show in the debug console, it shows in the "Output" tab (as shown below):

![image](https://user-images.githubusercontent.com/3181232/39547847-04358e62-4e16-11e8-85d1-98c1b9d98d2a.png)

**Comment by willmcgugan** [comment] 2018-05-02 20:57
Nothing it the Output tab either. I set the path to "/usr/local/bin/black",  where black v18.4a4 is installed.

**Comment by joslarson** [comment] 2018-05-03 15:42
So I'm assuming running `/usr/local/bin/black --help` in your terminal works? The fact that the debug output isn't working with `"black.debug": true` makes me think the extension might not be loading. Can you try disabling all other extensions so that black is only one (remember to reload VS Code after disabling the other extensions).

**Comment by willmcgugan** [comment] 2018-05-03 15:56
Yeah, I see the options from the black command, so black has to be installed.

Tried disabling other extensions, but no luck. When I do 'Format Document' I do see "black - Python code formatter" in the drop-down on the Output tab. But nothing else.

<img width="1019" alt="screen shot 2018-05-03 at 16 55 12" src="https://user-images.githubusercontent.com/554369/39588029-d0e71728-4ef2-11e8-9e90-94b032050d8d.png">

**Comment by joslarson** [comment] 2018-05-03 16:13
Dang, sorry about this, I'm really at a loss. I've setup my environment the same as you as far as I can tell and just can't seem to reproduce the issue. Would you mind posting your user settings file (and workspace settings if you have any).

**Comment by willmcgugan** [comment] 2018-05-03 16:20
No worries, I appreciate the effort.

Current user settings (nothing in workspace):

```
// Place your settings in this file to overwrite the default settings
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/__*__/": true,
        "**/.*": true,
        "**/*.pyc": true
    },
    "editor.fontSize": 10,
    "window.zoomLevel": 0,
    "[python]": {},
    "editor.minimap.enabled": false,
    "workbench.colorTheme": "Monokai",
    "editor.rulers": [72, 79, 120],
    "black.lineLength": 80,
    "workbench.iconTheme": "vscode-icons",
    "python.pythonPath": "/usr/local/bin/python3",
    "editor.renderWhitespace": "none",
    "files.trimTrailingWhitespace": true,
    "python.linting.mypyEnabled": true,
    "python.linting.pylintUseMinimalCheckers": false,
    "python.venvPath": "/Users/will/venvs/",
    "python.linting.flake8Args": [
        "--max-line-length=120"
    ],
    "python.linting.flake8Enabled": true,
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": false,
    "black.debug": true,
    "black.path": "/usr/local/bin/black"
}
```

**Comment by naphta** [comment] 2018-05-04 08:04
I'm actually getting a similar issue; works from terminal, settings autocomplete, I get the debug log selector but nothing in the actual log. Setting fast doesn't help either.

**Comment by joslarson** [comment] 2018-05-04 16:31
@willmcgugan @naphta I just pushed an update  (v2.0.4) that fixed the issue with the debug output hanging. It likely won't solve your actual issue, but now we should be able to see a helpful error message.

**Comment by willmcgugan** [comment] 2018-05-08 08:32
Progress! looks like an environment var issue...

```
Failed to format: unhandled error.
Command "/usr/local/bin/black -l 80 -" resulted in an exit code of 1.
Error: Command failed: /usr/local/bin/black -l 80 -
Traceback (most recent call last):
  File "/usr/local/bin/black", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales where
discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
```

Same command works from a terminal. I'm guessing you will need to copy over some env vars when you launch black in the extension?

**Comment by naphta** [comment] 2018-05-08 08:40
Yep same problem for me too.

```
Failed to format: unhandled error.
Command "/usr/local/bin/black -l 100 --fast -" resulted in an exit code of 1.
Error: Command failed: /usr/local/bin/black -l 100 --fast -
Traceback (most recent call last):
  File "/usr/local/bin/black", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/local/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales where
discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
```

Naturally if I hack my path to be: `export LC_ALL=en_GB.UTF-8;export LANG=en_GB.UTF-8;/usr/local/bin/black` then it does work as expected.

My VS Code terminal does have $LANG correctly set:

```
echo $LANG
en_GB.UTF-8
```

EDIT:

I did a small amount of digging and this seems to be a problem with VS Code; https://github.com/Microsoft/vscode/issues/16261 since we have a hacky workaround I suppose the fix is to wait for this to be resolved.

**Comment by joslarson** [comment] 2018-05-08 15:21
@naphta nice find! I'm actually able to reproduce the issue now. The reason I wasn't seeing it before is because I always open VS Code from my terminal using the `code` command, and when code opens as a subprocess of my shell it correctly inherits my locale settings. But if I just launch VS Code from my dock or finder I get issue described at Microsoft/vscode#16261

@willmcgugan I'm going to change the title on this and leave it open to help others more easily find the work around to this issue.

**Comment by joslarson** [comment] 2018-05-08 17:21
@willmcgugan @naphta I found a way to fix the issue in the extension. I just pushed v2.0.5 with the fix. I'm going to close this, but if you still have an issue, I can reopen it. Thanks for both of your help on this :)

**Closed as completed by joslarson** 2018-05-08 17:21 UTC

**Comment by naphta** [comment] 2018-05-23 11:31
Just to add to this thread, there's a better workaround for this problem in macOS.

```sh
$ launchctl setenv LC_ALL $LANG
$ killall Dock
```

**Comment by joslarson** [comment] 2018-05-23 14:07
@naphta is it not working out of the box for you on macOS now? The fix/hack I pushed should set LANG for you (when it's missing) based on macOS's system setting:

https://github.com/joslarson/black-vscode/commit/b3c6a097cb4e4aa1cf3d0bc6d2f87a6c95e5960d#diff-45327f86d4438556066de133327f4ca2R35

**Comment by naphta** [comment] 2018-05-23 14:22
@joslarson Absolutely fine since that commit you put in. I thought I'd just whack that workaround here just incase anyone discovers it. It also does solve some issues with other plugins (e.g. pipenv with python vscode breaks when launched from the dock)

**Comment by joslarson** [comment] 2018-05-23 15:05
@naphta okay cool. Just wanted to make sure it is working as expected for you :)
