### ISSUE TITLE
CLI output appended to source file

### ISSUE THREAD

**Issue by alexkahn** [joslarson/black-vscode#16] opened 2018-06-06 18:01 UTC
Hello 👋!

Thanks for making this extension - it works spectacularly!

I'm noticing that when I run the format document command in VSCode, there is a line appended to my source code:

```
1 file reformatted.
```

I ran the Black CLI on the same file and noticed the same output from there.

```
reformatted utils/redis.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

I am using version 2.0.5 of the extension and version 18.6b0 of Black, running on macOS with VSCode version 1.23.1

Let me know if there are any other details you want - I gave a quick browse of the source here and didn't immediately see where this could be coming from. Happy to give a hand with a PR.

Cheers!

**Comment by joslarson** [comment] 2018-06-11 16:46
@alexkahn Thanks for taking time to submit this issue :) looks like this was a regression in Black v18.6b0, updating to the latest Black beta should solve your problems. Also, FYI, Black formatting support just landed in the latest official Python extension, so you might want to switch to that. My plan all along has been to deprecate this extension once the official Python extension added support for Black. Let me know if there's any reason I shouldn't go ahead with that course of action.

**Closed as completed by joslarson** 2018-06-11 16:46 UTC
